import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { ptBR } from "@clerk/localizations";
import { View } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const appearance = {
  variables: {
    colorPrimary: "#db2777", // Rosa escuro (botões, links)
    colorBackground: "#fff1f2", // Fundo do modal
    colorText: "#111827", // Texto padrão
    colorInputBackground: "#ffffff", // Fundo dos campos de input
    borderRadius: "0.5rem", // Arredondamento geral
    fontFamily: "Inter, sans-serif",
  },
  elements: {
    card: "shadow-lg border border-blue-200 bg-blue-50", // Card (área principal do modal)
    headerTitle: "text-xl text-blue-800 font-bold",
    formButtonPrimary: "bg-blue-600 hover:bg-blue-700 text-white font-semibold",
    formFieldInput: "bg-white border-blue-400 focus:border-blue-600",
    footerActionText: "text-sm text-gray-500",
    footerActionLink: "text-blue-600 hover:underline",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={appearance} localization={ptBR}>
      <html lang="pt-br" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex min-h-screen flex-col">
            <Header />
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main className="flex-1">{children}</main>
            </ThemeProvider>
            <Footer />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
